services:
  3xui-shopbot:
    build: .
    restart: unless-stopped
    ports:
      - '1488:1488'
    volumes:
      - .:/app/project
    container_name: 3xui-shopbot-ssl-disabled
    environment:
      # Автоматический запуск ботов при старте контейнера
      # "both" или "1" — запустить ОБА бота (основной + support)
      SHOPBOT_AUTO_START: "both"

